use_frameworks!

target 'SKSpriteButton_Example' do
  pod 'SKSpriteButton', :path => '../'

  target 'SKSpriteButton_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2' 
  end
end
